[server]
# Server configuration
headless = true

[browser]
# Browser configuration
gatherUsageStats = false

[theme]
# Theme configuration
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
# Client configuration
toolbarMode = "minimal"
showErrorDetails = true

[runner]
# Runner configuration
magicEnabled = true

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s %(message)s"
