# Streamlit secrets configuration
# Copy this file to .streamlit/secrets.toml and fill in your actual API keys

[openai]
api_key = "your_openai_api_key_here"
model = "gpt-4"
embedding_model = "text-embedding-ada-002"

[pinecone]
api_key = "your_pinecone_api_key_here"
environment = "your_pinecone_environment_here"
index_name = "qa-bot-index"

[database]
url = "sqlite:///./qa_bot.db"

[app]
name = "QA Bot"
version = "1.0.0"
debug = true
page_title = "QA Bot - Document Question Answering"
page_icon = "🤖"

[processing]
chunk_size = 1024
chunk_overlap = 200
similarity_top_k = 5
confidence_threshold = 0.7

[upload]
max_file_size_mb = 50
allowed_file_types = ["pdf"]
max_files_per_upload = 100
upload_directory = "./uploads"
